---
- hosts: Juniper_Routers
  gather_facts: no
  connection: local

  tasks:
    - name: Render config for host
      template:
        src: "templates/template.j2"
        dest: "out/{{ inventory_hostname }}.cfg"